version: "3.9"

networks:
  int_network:

services:
  prescriptionsData_webservicerest:
    image: paim2021/paim_proj_prescriptions:prescriptions_latest
    ports:
      - 8081:80
      - 44301:443
    networks:
      - int_network
    deploy:
      replicas: 1

  visitsData_webservicerest:
    image: paim2021/paim_proj_visits:visits_latest
    ports:
      - 8082:80
      - 44302:443
    networks:
      - int_network
    deploy:
      replicas: 1

  patientsData_webservicerest:
    image: paim2021/paim_proj_patients:patients_latest
    ports:
      - 8083:80
      - 44303:443
    networks: 
      - int_network
    deploy:
      replicas: 1

  doctorApp_webservicerest:
    image: paim2021/paim_proj_doctor_app:doctor_app_latest
    environment: 
      - visitsServiceGetVisits=http://visitsData_webservicerest/GetVisits?doctorId=
      - prescriptionsServiceGetAllPrescriptions=http://prescriptionsData_webservicerest/GetAllPrescriptions
      - prescriptionsServiceGetPrescription=http://prescriptionsData_webservicerest/GetPrescription?patientId=
      - prescriptionsServiceAddPrescription=http://prescriptionsData_webservicerest/AddPrescription
      - patientsServiceGetAllPatients=http://patientsData_webservicerest/GetAllPatients
      - patientsServiceGetPatientByPesel=http://patientsData_webservicerest/GetPatientByPesel?pesel=
    ports:
      - 8080:80
      - 44300:443
    networks:
      - int_network
    deploy:
      replicas: 1
    depends_on:
      - prescriptionsData_webservicerest
      - visitsData_webservicerest
      - patientsData_webservicerest
